services:
  ordermanagement.webapi:
    image: ${DOCKER_REGISTRY-}ordermanagementwebapi
    build:
      context: .
      dockerfile: OrderManagement.WebAPI/Dockerfile
    ports:
      - "29701:8080"
      - "29702:8081"
    networks:
     - ordermanagementnetwork
  mongodb:
    image: mongo:8.0.3
    container_name: ordermanagement-mongodb
    volumes:
        - "D:\\Docker\\Volumes\\OrderManagement:/data/db"
    ports:
        - "29700:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=ordermnguser
        - MONGO_INITDB_ROOT_PASSWORD=12345678Aa
    networks:
     - ordermanagementnetwork
  redis:
    image: redis:7.4-alpine
    container_name: ordermanagement-redis
    ports:
      - "6379:6379"
    networks:
      - ordermanagementnetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
networks:
  ordermanagementnetwork:
    driver: bridge
